### ISSUE TITLE
can not build vue project when i update from 0.16.x to 0.17.6

### ISSUE THREAD

**Issue by leeboo** [daybrush/moveable#240]
## Environments
* Framework name: Vue
* Framework version: 2.x
* Moveable Component version: 0.17.6

can not build vue project when i update from 0.16.x to 0.17.6 ,
what does i missing?
:
`ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/@types/react/index.d.ts(118,31):
118:31 Type 'T' does not satisfy the constraint 'string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)'.
  Type 'string | number | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)' is not assignable to type 'string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)'.
    Type 'number' is not assignable to type 'string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)'.
      Type 'T' is not assignable to type 'string'.
        Type 'string | number | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)' is not assignable to type 'string'.
          Type 'number' is not assignable to type 'string'.
    116 |         T extends keyof JSX.IntrinsicElements | JSXElementConstructor<any>,
    117 |         P = Pick<ComponentProps<T>, Exclude<keyof ComponentProps<T>, 'key' | 'ref'>>
  > 118 |     > extends ReactElement<P, T> { }
        |                               ^
    119 | 
    120 |     /**
    121 |      * @deprecated Please use `FunctionComponentElement`
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/@types/react/index.d.ts(2897,19):
2897:19 Interface 'Element' cannot simultaneously extend types 'ReactElement<any, any>' and 'VNode'.
  Named property 'key' of types 'ReactElement<any, any>' and 'VNode' are not identical.
    2895 |     namespace JSX {
    2896 |         // tslint:disable-next-line:no-empty-interface
  > 2897 |         interface Element extends React.ReactElement<any, any> { }
         |                   ^
    2898 |         interface ElementClass extends React.Component<any> {
    2899 |             render(): React.ReactNode;
    2900 |         }
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-moveable/src/react-moveable/ables/Groupable.tsx(20,20):
20:20 JSX element type 'MoveableManager<{ key: string; ref: (e: any) => void; target: AnimateElement; origin: false; parentMoveable: MoveableGroup; parentPosition: { left: any; top: any; }; }, {}>' is not a constructor function for JSX elements.
  Type 'MoveableManager<{ key: string; ref: (e: any) => void; target: AnimateElement; origin: false; parentMoveable: MoveableGroup; parentPosition: { left: any; top: any; }; }, {}>' is missing the following properties from type 'ElementClass': $el, $options, $parent, $root, and 26 more.
    18 | 
    19 |         return targets.map((target, i) => {
  > 20 |             return <MoveableManager
       |                    ^
    21 |                 key={"moveable" + i}
    22 |                 ref={refs(moveable, "moveables", i)}
    23 |                 target={target}
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-moveable/src/react-moveable/MoveableManager.tsx(108,13):
108:13 JSX element type '{ element: HTMLElement; injectResult: InjectResult | null; render(): DOMElement<{ children?: ReactNode; ref: (e: any) => void; className: string; }, any>; ... 8 more ...; refs: { ...; }; }' is not a constructor function for JSX elements.
  Type '{ element: HTMLElement; injectResult: InjectResult | null; render(): DOMElement<{ children?: ReactNode; ref: (e: any) => void; className: string; }, any>; ... 8 more ...; refs: { ...; }; }' is missing the following properties from type 'ElementClass': $el, $options, $parent, $root, and 26 more.
    106 | 
    107 |         return (
  > 108 |             <ControlBoxElement
        |             ^
    109 |                 ref={ref(this, "controlBox")}
    110 |                 className={`${prefix("control-box", direction === -1 ? "reverse" : "")} ${className}`} style={{
    111 |                     "position": "absolute",
`

**Comment by leeboo** [comment]
i found i add three package and then can not build：
    "@daybrush/drag": "^0.15.0",
    "@daybrush/utils": "^0.10.4",
    "selecto": "^1.1.2",
can you give me any idea?

**Comment by leeboo** [comment]
i test package one by one, found if installed package "@daybrush/drag": "^0.15.0, then build failed

**Comment by daybrush** [comment]
@leeboo 
Oh. Thank you. I'll check it.

**Comment by daybrush** [comment]
@leeboo 


* `moveable` 0.17.7
* `react-moveable` 0.20.8
* `preact-moveable` 0.19.8
* `ngx-moveable` 0.13.8
* `svelte-moveable` 0.8.8


moveable's new version is released. Check it again.

**Comment by leeboo** [comment]
hi @daybrush thank you for you awesome jobs, but still can not build, i tried reinstall all package :
![image](https://user-images.githubusercontent.com/1256745/83326632-3aa02280-a2a8-11ea-883f-844ba40fa7d5.png)
![image](https://user-images.githubusercontent.com/1256745/83326652-50ade300-a2a8-11ea-8169-17f4fe54bc9b.png)

my package.json:
`    "@daybrush/drag": "^0.15.0",
    "@popperjs/core": "^2.4.0",
    "@scena/guides": "^0.6.0",
    "react-compat-css-styled": "^0.1.3",
    "react-simple-compat": "^0.1.7",
    "keycon": "^0.8.0",
    "moveable": "^0.17.7",
    "animate.css": "^3.7.2",
    "awesome-bootstrap-checkbox": "^1.0.1",
    "bootstrap": "^4.5.0",
    "core-js": "^3.6.5",
    "cssgram": "^0.1.3",
    "dom-to-image": "^2.6.0",
    "echarts": "^4.8.0",
    "gradient-parser": "^0.1.5",
    "imagesloaded": "^4.1.4",
    "ion-rangeslider": "^2.3.1",
    "jquery": "^3.5.1",
    "jquery-bridget": "^2.0.1",
    "masonry-layout": "^4.2.2",
    "popper.js": "^1.16.1",
    "register-service-worker": "^1.7.1",
    "scenejs": "^1.1.7",
    "scss": "^0.2.4",
    "selecto": "^1.1.2",
    "sortablejs": "^1.10.2",
    "svgedit": "^5.1.0",
    "tinycolor2": "^1.4.1",
    "unit-to-px": "^1.0.5",
    "vue": "^2.6.11",
    "vue-class-component": "^7.2.2",
    "vue-color": "^2.7.1",
    "vue-property-decorator": "^8.4.2",
    "vue-router": "^3.2.0",
    "vue-upload-component": "^2.8.20",
    "vuex": "^3.4.0",
    "vxe-table": "^2.9.9",
    "xe-utils": "^2.4.5"`

**Comment by daybrush** [comment]
@leeboo 

I think that node_modules src folder must not included.  

Why include this folder? Check tsconfig or settings. And update all daybrush project. @scena/guides

**Comment by leeboo** [comment]
the tsconfig.json config is:
    "paths": {
      "@/*": [
        "src/*"
      ]
    }
so how to change this to compatible with daybrush modules
thanks

**Comment by daybrush** [comment]
@leeboo 


Is there a folder related to node_modules in move in tsconfig?

**Comment by leeboo** [comment]
i think have not, this is my tsconfig.json
`{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "noImplicitThis": false,
    "noImplicitAny": false,
    "strict": true,
    "jsx": "preserve",
    "importHelpers": true,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": false,
    "baseUrl": ".",
    "types": [
      "webpack-env",
      "jest"
    ],
    "paths": {
      "@/*": [
        "src/*"
      ]
    },
    "lib": [
      "esnext",
      "dom",
      "dom.iterable",
      "scripthost"
    ]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "tests/**/*.ts",
    "tests/**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ]
}
`

**Comment by leeboo** [comment]
i found src/shims-tsx.d.ts have one code，if i comment it, this error is missing
![image](https://user-images.githubusercontent.com/1256745/83766304-d4077400-a6ae-11ea-924d-516b8323c8b3.png)

**Comment by daybrush** [comment]
@leeboo 

Would you show me the package.lock?
Show everything related to `@types/react`, `@types/react-dom`

ex)
```js
 "@types/react-dom": {
      "version": "16.9.8",
      "resolved": "https://registry.npmjs.org/@types/react-dom/-/react-dom-16.9.8.tgz",
      "integrity": "....",
      "dev": true,
      "requires": {
        "@types/react": "*"
      }
    },
```

**Comment by leeboo** [comment]
```
    "@types/react": {
      "version": "16.9.35",
      "resolved": "https://registry.npmjs.org/@types/react/-/react-16.9.35.tgz",
      "integrity": "sha512-q0n0SsWcGc8nDqH2GJfWQWUOmZSJhXV64CjVN5SvcNti3TdEaA3AH0D8DwNmMdzjMAC/78tB8nAZIlV8yTz+zQ==",
      "requires": {
        "@types/prop-types": "*",
        "csstype": "^2.2.0"
      }
    },

    "react-compat-guides": {
      "version": "0.3.0",
      "resolved": "https://registry.npmjs.org/react-compat-guides/-/react-compat-guides-0.3.0.tgz",
      "integrity": "sha512-qHCOoyJstJZ4ITd/+4wbDrhTHQO7aq/DlNaByKEG7MtjQ44sd+lNSBXui0zbYwLzB6Mo3zgijtsdz8huVxhbfA==",
      "requires": {
        "@scena/react-guides": "^0.5.0",
        "@types/react": "^16.0.0",
        "react-compat-css-styled": "^0.1.2",
        "react-compat-ruler": "^0.2.0",
        "react-simple-compat": "^0.1.4"
      }
    },

    "react-compat-ruler": {
      "version": "0.2.0",
      "resolved": "https://registry.npmjs.org/react-compat-ruler/-/react-compat-ruler-0.2.0.tgz",
      "integrity": "sha512-hnHn77nDNixGlhxVVXLYYVnwbgRY+EoGM9KdTGeZi6UmNFnOpk15R/V4+8elTkc7734qZCEC4/wQM5U5TsrY3Q==",
      "requires": {
        "@scena/react-ruler": "^0.3.0",
        "@types/react": "^16.9.17",
        "react-simple-compat": "^0.1.4"
      }
    },
```

not found any info about @types/react-dom

**Comment by daybrush** [comment]
@leeboo 

Update `@scena/guides` (current 0.7.2)

**Comment by leeboo** [comment]
after update @scena/guides to 0.7.2, i got more errors:
```
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-css-styled/declaration/styled.d.ts(1,23):
1:23 Cannot find type definition file for 'react'.
  > 1 | /// <reference types="react" />
      |                       ^
    2 | import { IObject } from "@daybrush/utils";
    3 | import { InjectResult } from "css-styled";
    4 | export default function styled<T extends HTMLElement | SVGElement = HTMLElement>(Tag: string, css: string): {
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-css-styled/declaration/styled.d.ts(8,26):
8:26 Cannot find module 'react'.
     6 |         element: T;
     7 |         injectResult: InjectResult | null;
  >  8 |         render(): import("react").DOMElement<{
       |                          ^
     9 |             children?: import("react").ReactNode;
    10 |             ref: (e: any) => void;
    11 |             className: string;
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-css-styled/declaration/styled.d.ts(20,31):
20:31 Cannot find module 'react'.
    18 |         forceUpdate(callBack?: (() => void) | undefined): void;
    19 |         readonly props: Readonly<IObject<any>> & Readonly<{
  > 20 |             children?: import("react").ReactNode;
       |                               ^
    21 |         }>;
    22 |         state: Readonly<{}>;
    23 |         refs: {
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-css-styled/declaration/styled.d.ts(24,35):
24:35 Cannot find module 'react'.
    22 |         state: Readonly<{}>;
    23 |         refs: {
  > 24 |             [key: string]: import("react").ReactInstance;
       |                                   ^
    25 |         };
    26 |     };
    27 |     new (props: IObject<any>, context?: any): {
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-css-styled/declaration/styled.d.ts(30,26):
30:26 Cannot find module 'react'.
    28 |         element: T;
    29 |         injectResult: InjectResult | null;
  > 30 |         render(): import("react").DOMElement<{
       |                          ^
    31 |             children?: import("react").ReactNode;
    32 |             ref: (e: any) => void;
    33 |             className: string;
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-css-styled/declaration/styled.d.ts(42,31):
42:31 Cannot find module 'react'.
    40 |         forceUpdate(callBack?: (() => void) | undefined): void;
    41 |         readonly props: Readonly<IObject<any>> & Readonly<{
  > 42 |             children?: import("react").ReactNode;
       |                               ^
    43 |         }>;
    44 |         state: Readonly<{}>;
    45 |         refs: {
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-css-styled/declaration/styled.d.ts(46,35):
46:35 Cannot find module 'react'.
    44 |         state: Readonly<{}>;
    45 |         refs: {
  > 46 |             [key: string]: import("react").ReactInstance;
       |                                   ^
    47 |         };
    48 |     };
    49 |     contextType?: import("react").Context<any> | undefined;
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-css-styled/declaration/styled.d.ts(49,26):
49:26 Cannot find module 'react'.
    47 |         };
    48 |     };
  > 49 |     contextType?: import("react").Context<any> | undefined;
       |                          ^
    50 | };
    51 | 
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-css-styled/declaration/types.d.ts(1,24):
1:24 Cannot find module 'react'.
  > 1 | import * as React from "react";
      |                        ^
    2 | import { IObject } from "@daybrush/utils";
    3 | export interface StyledInterface<T = HTMLElement | SVGElement> extends React.Component<IObject<any>> {
    4 |     getElement(): T;
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-moveable/src/react-moveable/ables/Groupable.tsx(13,34):
13:34 Property 'props' does not exist on type 'MoveableGroup'.
    11 |     },
    12 |     render(moveable: MoveableGroup, React: Renderer): any[] {
  > 13 |         const targets = moveable.props.targets || [];
       |                                  ^
    14 | 
    15 |         moveable.moveables = [];
    16 |         const { left, top } = moveable.state;
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-moveable/src/react-moveable/ables/Groupable.tsx(20,20):
20:20 JSX element type 'MoveableManager<{}, {}>' is not a constructor function for JSX elements.
  Type 'MoveableManager<{}, {}>' is missing the following properties from type 'ElementClass': $el, $options, $parent, $root, and 26 more.
    18 | 
    19 |         return targets.map((target, i) => {
  > 20 |             return <MoveableManager
       |                    ^
    21 |                 key={"moveable" + i}
    22 |                 ref={refs(moveable, "moveables", i)}
    23 |                 target={target}
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-moveable/src/react-moveable/ables/triggerRender.ts(17,35):
17:35 Property 'props' does not exist on type 'MoveableManager<any, {}>'.
    15 | 
    16 |     if (isGroup) {
  > 17 |         params.targets = moveable.props.targets;
       |                                   ^
    18 |     }
    19 |     triggerEvent<any>(moveable, `onRender${eventAffix}Start`, params);
    20 | }
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-moveable/src/react-moveable/ables/triggerRender.ts(33,35):
33:35 Property 'props' does not exist on type 'MoveableManager<any, {}>'.
    31 | 
    32 |     if (isGroup) {
  > 33 |         params.targets = moveable.props.targets;
       |                                   ^
    34 |     }
    35 |     triggerEvent<any>(moveable, `onRender${eventAffix}`, params);
    36 | }
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-moveable/src/react-moveable/ables/triggerRender.ts(50,35):
50:35 Property 'props' does not exist on type 'MoveableManager<any, {}>'.
    48 | 
    49 |     if (isGroup) {
  > 50 |         params.targets = moveable.props.targets;
       |                                   ^
    51 |     }
    52 |     triggerEvent<any>(moveable, `onRender${eventAffix}End`, params);
    53 | }
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-moveable/src/react-moveable/getAbleDragger.ts(88,18):
88:18 Property 'forceUpdate' does not exist on type 'MoveableManager<any, {}>'.
    86 |     }
    87 |     if (((!isStart && isUpdate) || (isEnd && !isUpdate)) && !isReqeust) {
  > 88 |         moveable.forceUpdate();
       |                  ^
    89 |     }
    90 |     if (!isStart && !isEnd && !isAfter && isUpdate) {
    91 |         triggerAble(moveable, ableType, eventOperation, eventAffix, eventType + "After", e);
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-moveable/src/react-moveable/getAbleDragger.ts(105,19):
105:19 Property 'props' does not exist on type 'MoveableManager<T, {}>'.
    103 |     targets.push(controlBox);
    104 | 
  > 105 |     if (!moveable.props.dragArea) {
        |                   ^
    106 |         targets.push(moveableTarget);
    107 |     }
    108 | 
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-moveable/src/react-moveable/getAbleDragger.ts(134,18):
134:18 Property 'props' does not exist on type 'MoveableManager<T, {}>'.
    132 |         pinchOutside,
    133 |         pinchThreshold,
  > 134 |     } = moveable.props;
        |                  ^
    135 |     const options: IObject<any> = {
    136 |         container: window,
    137 |         pinchThreshold,
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-moveable/src/react-moveable/MoveableGroup.tsx(108,28):
108:28 Property 'props' does not exist on type 'MoveableGroup'.
    106 |     public updateEvent(prevProps: MoveableManagerProps<GroupableProps>) {
    107 |         const state = this.state;
  > 108 |         const props = this.props;
        |                            ^
    109 | 
    110 |         if (!state.target) {
    111 |             state.target = this.areaElement;
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-moveable/src/react-moveable/MoveableGroup.tsx(141,28):
141:28 Property 'props' does not exist on type 'MoveableGroup'.
    139 | 
    140 |         const state = this.state;
  > 141 |         const props = this.props;
        |                            ^
    142 |         const target = state.target! || props.target!;
    143 | 
    144 |         if (!isTarget || (type !== "" && props.updateGroup)) {
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-moveable/src/react-moveable/MoveableGroup.tsx(162,18):
162:18 Property 'props' does not exist on type 'MoveableGroup'.
    160 |             this.controlBox.getElement(),
    161 |             this.getContainer(),
  > 162 |             this.props.rootContainer || container,
        |                  ^
    163 |             state,
    164 |         );
    165 |         const pos = [info.left!, info.top!];
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-moveable/src/react-moveable/MoveableGroup.tsx(195,36):
195:36 Property 'props' does not exist on type 'MoveableGroup'.
    193 |     }
    194 |     protected updateAbles() {
  > 195 |         super.updateAbles([...this.props.ables!, Groupable], "Group");
        |                                    ^
    196 |     }
    197 | }
    198 | 
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-moveable/src/react-moveable/MoveableManager.tsx(1,24):
1:24 Cannot find module 'react'.
  > 1 | import * as React from "react";
      |                        ^
    2 | import { MOVEABLE_CSS, PREFIX } from "./consts";
    3 | import {
    4 |     prefix, getLineStyle,
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-moveable/src/react-moveable/MoveableManager.tsx(95,28):
95:28 Property 'props' does not exist on type 'MoveableManager<T, U>'.
    93 | 
    94 |     public render() {
  > 95 |         const props = this.props;
       |                            ^
    96 |         const state = this.state;
    97 |         const { edge, parentPosition, className, target: propsTarget, zoom } = props;
    98 | 
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-moveable/src/react-moveable/MoveableManager.tsx(108,13):
108:13 JSX element type '{ element: HTMLElement; injectResult: InjectResult | null; render(): any; componentDidMount(): void; componentWillUnmount(): void; getElement(): HTMLElement; ... 5 more ...; refs: { ...; }; }' is not a constructor function for JSX elements.
  Type '{ element: HTMLElement; injectResult: InjectResult | null; render(): any; componentDidMount(): void; componentWillUnmount(): void; getElement(): HTMLElement; ... 5 more ...; refs: { ...; }; }' is missing the following properties from type 'ElementClass': $el, $options, $parent, $root, and 26 more.
    106 | 
    107 |         return (
  > 108 |             <ControlBoxElement
        |             ^
    109 |                 ref={ref(this, "controlBox")}
    110 |                 className={`${prefix("control-box", direction === -1 ? "reverse" : "")} ${className}`} style={{
    111 |                     "position": "absolute",
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-moveable/src/react-moveable/MoveableManager.tsx(127,28):
127:28 Property 'props' does not exist on type 'MoveableManager<T, U>'.
    125 |     public componentDidMount() {
    126 |         this.controlBox.getElement();
  > 127 |         const props = this.props;
        |                            ^
    128 |         const { parentMoveable, container } = props;
    129 | 
    130 |         this.updateEvent(props);
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-moveable/src/react-moveable/MoveableManager.tsx(144,52):
144:52 Property 'props' does not exist on type 'MoveableManager<T, U>'.
    142 |     }
    143 |     public getContainer(): HTMLElement | SVGElement {
  > 144 |         const { parentMoveable, container } = this.props;
        |                                                    ^
    145 | 
    146 |         return container!
    147 |             || (parentMoveable && parentMoveable.getContainer())
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-moveable/src/react-moveable/MoveableManager.tsx(216,28):
216:28 Property 'props' does not exist on type 'MoveableManager<T, U>'.
    214 |     }
    215 |     public updateRect(type?: "Start" | "" | "End", isTarget?: boolean, isSetState: boolean = true) {
  > 216 |         const props = this.props;
        |                            ^
    217 |         const parentMoveable = props.parentMoveable;
    218 |         const state = this.state;
    219 |         const target = (state.target || this.props.target) as HTMLElement | SVGElement;
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-moveable/src/react-moveable/MoveableManager.tsx(219,46):
219:46 Property 'props' does not exist on type 'MoveableManager<T, U>'.
    217 |         const parentMoveable = props.parentMoveable;
    218 |         const state = this.state;
  > 219 |         const target = (state.target || this.props.target) as HTMLElement | SVGElement;
        |                                              ^
    220 |         const container = this.getContainer();
    221 |         const rootContainer = parentMoveable
    222 |             ? parentMoveable.props.rootContainer
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-moveable/src/react-moveable/MoveableManager.tsx(235,28):
235:28 Property 'props' does not exist on type 'MoveableManager<T, U>'.
    233 |         const hasTargetAble = this.targetAbles.length;
    234 |         const hasControlAble = this.controlAbles.length;
  > 235 |         const props = this.props;
        |                            ^
    236 |         const target = props.dragTarget || props.target;
    237 |         const prevTarget = prevProps.dragTarget || prevProps.target;
    238 |         const dragArea = props.dragArea;
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-moveable/src/react-moveable/MoveableManager.tsx(304,43):
304:43 Property 'props' does not exist on type 'MoveableManager<T, U>'.
    302 |     }
    303 |     public request(ableName: string, param: IObject<any> = {}, isInstant?: boolean): Requester {
  > 304 |         const { ables, groupable } = this.props as any;
        |                                           ^
    305 |         const requsetAble: Able = ables!.filter((able: Able) => able.name === ableName)[0];
    306 | 
    307 |         if (this.isDragging() || !requsetAble || !requsetAble.request) {
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-moveable/src/react-moveable/MoveableManager.tsx(349,28):
349:28 Property 'props' does not exist on type 'MoveableManager<T, U>'.
    347 |     public updateRenderPoses() {
    348 |         const state = this.state;
  > 349 |         const props = this.props;
        |                            ^
    350 |         const {
    351 |             beforeOrigin, transformOrigin,
    352 |             matrix, is3d, pos1, pos2, pos3, pos4, left: stateLeft, top: stateTop } = state;
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-moveable/src/react-moveable/MoveableManager.tsx(370,60):
370:60 Property 'props' does not exist on type 'MoveableManager<T, U>'.
    368 |     }
    369 |     public checkUpdate() {
  > 370 |         const { target, container, parentMoveable } = this.props;
        |                                                            ^
    371 |         const {
    372 |             target: stateTarget,
    373 |             container: stateContainer,
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-moveable/src/react-moveable/MoveableManager.tsx(394,32):
394:32 Property 'props' does not exist on type 'MoveableManager<T, U>'.
    392 |     }
    393 |     public triggerEvent(name: string, e: any): any {
  > 394 |         const callback = (this.props as any)[name];
        |                                ^
    395 | 
    396 |         return callback && callback(e);
    397 |     }
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-moveable/src/react-moveable/MoveableManager.tsx(406,18):
406:18 Property 'forceUpdate' does not exist on type 'MoveableManager<T, U>'.
    404 |             return false;
    405 |         }).length) {
  > 406 |             this.forceUpdate();
        |                  ^
    407 |         }
    408 |     }
    409 |     protected updateAbles(
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-moveable/src/react-moveable/MoveableManager.tsx(410,30):
410:30 Property 'props' does not exist on type 'MoveableManager<T, U>'.
    408 |     }
    409 |     protected updateAbles(
  > 410 |         ables: Able[] = this.props.ables!,
        |                              ^
    411 |         eventAffix: string = "",
    412 |     ) {
    413 |         const props = this.props as any;
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-moveable/src/react-moveable/MoveableManager.tsx(413,28):
413:28 Property 'props' does not exist on type 'MoveableManager<T, U>'.
    411 |         eventAffix: string = "",
    412 |     ) {
  > 413 |         const props = this.props as any;
        |                            ^
    414 |         const triggerAblesSimultaneously = props.triggerAblesSimultaneously;
    415 |         const enabledAbles = ables!.filter(able => able && props[able.name]);
    416 | 
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-moveable/src/react-moveable/MoveableManager.tsx(429,18):
429:18 Property 'setState' does not exist on type 'MoveableManager<T, U>'.
    427 |     protected updateState(nextState: any, isSetState?: boolean) {
    428 |         if (isSetState) {
  > 429 |             this.setState(nextState);
        |                  ^
    430 |         } else {
    431 |             const state = this.state as any;
    432 | 
ERROR in /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/react-moveable/src/react-moveable/MoveableManager.tsx(439,28):
439:28 Property 'props' does not exist on type 'MoveableManager<T, U>'.
    437 |     }
    438 |     protected renderAbles() {
  > 439 |         const props = this.props as any;
        |                            ^
    440 |         const ables: Able[] = props.ables!;
    441 |         const triggerAblesSimultaneously = props.triggerAblesSimultaneously;
    442 |         const enabledAbles = ables.filter(able => able && props[able.name]);

```

**Comment by daybrush** [comment]
@leeboo 

The situation is not reproduced, but is the script different? What settings are different? Please check.

https://github.com/daybrush/vue-test

**Comment by leeboo** [comment]
i cloned vue-test and build it, but it's failed:

[https://github.com/daybrush/vue-test/issues/1](url)

node v12.2.0
npm  v6.14.5

**Comment by leeboo** [comment]
fixed at https://github.com/daybrush/vue-test/issues/1
thanks 👍
